//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckConsecutiveStudioRuns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckConsecutiveStudioRuns.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessRule.
        /// </summary>
        internal static string BusinessRule {
            get {
                return ResourceManager.GetString("BusinessRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleVoilation.
        /// </summary>
        internal static string LoggingProcess {
            get {
                return ResourceManager.GetString("LoggingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestProcess.
        /// </summary>
        internal static string ProcessNameToExecute {
            get {
                return ResourceManager.GetString("ProcessNameToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a correct number in the Maximum number of allowed consecutive runs input..
        /// </summary>
        internal static string RecommendationInputValidationErrorMessage {
            get {
                return ResourceManager.GetString("RecommendationInputValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Require publish after input is not a valid number..
        /// </summary>
        internal static string RequireAfterPublishInvalidInput {
            get {
                return ResourceManager.GetString("RequireAfterPublishInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string RequirePublishAfterParameterDefault {
            get {
                return ResourceManager.GetString("RequirePublishAfterParameterDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to require_publish_after.
        /// </summary>
        internal static string RequirePublishAfterParameterKey {
            get {
                return ResourceManager.GetString("RequirePublishAfterParameterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require project publish.
        /// </summary>
        internal static string RequirePublishAfterParameterName {
            get {
                return ResourceManager.GetString("RequirePublishAfterParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require project publish.
        /// </summary>
        internal static string RequirePublishRuleName {
            get {
                return ResourceManager.GetString("RequirePublishRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST-PUB-001.
        /// </summary>
        internal static string RuleId {
            get {
                return ResourceManager.GetString("RuleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to Orchestrator instead of running from Studio or StudioX..
        /// </summary>
        internal static string RuleRecommendation {
            get {
                return ResourceManager.GetString("RuleRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://marketplace.uipath.com/.
        /// </summary>
        internal static string UrlParameterDefault {
            get {
                return ResourceManager.GetString("UrlParameterDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        internal static string UrlParameterKey {
            get {
                return ResourceManager.GetString("UrlParameterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL for additional information.
        /// </summary>
        internal static string UrlParameterName {
            get {
                return ResourceManager.GetString("UrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your organization does not permit production runs from this tool. Please publish this project to Orchestrator immediately and run from your UiPath Assistant..
        /// </summary>
        internal static string WarningMessageParameterDefault {
            get {
                return ResourceManager.GetString("WarningMessageParameterDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning_message.
        /// </summary>
        internal static string WarningMessageParameterKey {
            get {
                return ResourceManager.GetString("WarningMessageParameterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning message.
        /// </summary>
        internal static string WarningMessageParameterName {
            get {
                return ResourceManager.GetString("WarningMessageParameterName", resourceCulture);
            }
        }
    }
}
